[local]
localhost ansible_connection=local

[windows]
pcwindows ansible_host=10.76.65.58

#variable for windows host
[windows:vars]
ansible_user=ansible
ansible_password='Harsh-Hab67@#'
ansible_connection=winrm
ansible_port=5986
ansible_winrm_scheme=https
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_shell_type=powershell

